- hosts: servers
  tasks:
    - name: rm .ssh
      file:
        path: '/home/{{item}}/.gitconfig'
        state: absent
      become: yes
      loop: 
        - sansa
        - robert
        - jaime