- hosts: appservers

  tasks:
    - name: chach update
      apt:
        update_cache: yes
      become: yes
      tags: updatecache

    - name: install git
      apt:
        name: git
        state: present
        update_cache: yes
      become: yes
      tags: installapps

    - name: install make
      apt:
        name: make
        state: present
        update_cache: yes
      become: yes
      tags: installapps

    - name: install nodejs
      apt:
        name: nodejs
        state: present
        update_cache: yes
      become: yes
      tags: installapps

    - name: create user
      user:
        name: arya
      tags: createusers

    - name: create user
      user:
        name: tirion
      tags: createusers

    - name: create user
      user: 
        name: sansa
      tags: createusers